-------------------------------------------------------------------------------
-- demo_shiny_chaining.lua
-------------------------------------------------------------------------------
-- Visual demo for the Gen 4 PokeRadar shiny-chain feature, intended to be
-- recorded via test/record_test.sh and clipped into a README GIF.
--
-- Unlike test_shiny_chaining.lua (which is memory-level and never leaves
-- the Pallet Town bedroom), this script actually drives the full feature
-- loop the player will see in-game:
--
--   1. Boot through character select to the overworld.
--   2. Warp the player to Route 1.
--   3. Walk UP into tall grass.
--   4. Open the bag via START -> BAG, switch to KEY ITEMS pocket,
--      select POKERADAR -> USE.
--   5. Four shaking grass patches spawn around the player.
--   6. Walk onto one of them to trigger the forced encounter.
--
-- The recording is expected to be cropped to the mGBA game window only
-- (0,0 -> 480x320 on the 1920x640 virtual display) when turning it into
-- a GIF, so the scripting window is not visible in the final asset.
--
-- HOW TO RUN (recording):
--   bash test/record_test.sh test/demos/demo_shiny_chaining.lua
-------------------------------------------------------------------------------

local script_dir = debug.getinfo(1, "S").source:match("@?(.*/)") or ""
local project_dir = script_dir .. "../../"

local fw   = dofile(project_dir .. "test/lib/framework.lua")
local ADDR = dofile(project_dir .. "test/lib/addresses.lua")
local cs   = dofile(project_dir .. "test/lib/character_select.lua")
local warp = dofile(project_dir .. "test/lib/warp.lua")
local pr   = dofile(project_dir .. "test/lib/poke_radar.lua")

local function current_map_packed()
    local sb1 = fw.read32(ADDR.gSaveBlock1Ptr)
    local mg = fw.read8(sb1 + ADDR.SB1_LOC_MAP_GROUP)
    local mn = fw.read8(sb1 + ADDR.SB1_LOC_MAP_NUM)
    return mg, mn
end

local function log_state(tag)
    local mg, mn = current_map_packed()
    local oeid = fw.read8(ADDR.gPlayerAvatar + ADDR.PA_OBJECT_EVENT_ID)
    local oa = ADDR.gObjectEvents + oeid * ADDR.OBJECT_EVENT_SIZE
    local x = fw.read16(oa + ADDR.OE_CURRENT_X)
    local y = fw.read16(oa + ADDR.OE_CURRENT_Y)
    fw.log(string.format(
        "[state %s] map=%d.%d pos=(%d,%d) magic=0x%08X chain=%d charges=%d flags=0x%02X",
        tag, mg, mn, x, y, pr.get_magic(), pr.get_chain_count(),
        pr.get_charges(), pr.get_flags()))
end

local ROUTE1_STATE = "/tmp/pokefirered-route1-grass.ss"

fw.run(function()
    fw.slow_down("demo recording runs at real-time for visibility")
    fw.wait_frames(30)

    fw.log("=== PokeRadar Shiny Chaining — Visual Demo ===")

    -- 1) Load the pre-built Route 1 save state. This is a shared fixture
    -- generated by test/tools/warp_to_route1.lua — running that script
    -- once creates /tmp/pokefirered-route1.ss. Starting from a fresh
    -- reset + boot would also work via warp.warp_to, but the post-warp
    -- field state is unstable for ~200 frames (input lock while scripts
    -- run), while a loaded state is immediately interactable.
    fw.log(">>> Loading Route 1 save state...")
    if not fw.try_load_state(ROUTE1_STATE) then
        fw.log_error("No Route 1 state at " .. ROUTE1_STATE
            .. " — run test/tools/warp_to_route1.lua first.")
        fw.finish()
        return
    end
    fw.wait_frames(120)
    fw.assert_true(cs.is_player_active(),
        "player ObjectEvent is active (state loaded on Route 1)")
    log_state("post-load")
    fw.screenshot("/tmp/mgba-demo-02-warp.png")

    -- The fixture state already places the player ON a tall-grass tile
    -- on Route 1 (exact column/row depends on when the fixture was last
    -- regenerated by test/tools/warp_to_route1_grass.lua). No walking
    -- needed before opening the bag — PokeRadar_IsUsableHere will return
    -- TRUE from whichever grass tile the fixture landed on.
    local oeid = fw.read8(ADDR.gPlayerAvatar + ADDR.PA_OBJECT_EVENT_ID)
    local oa = ADDR.gObjectEvents + oeid * ADDR.OBJECT_EVENT_SIZE
    local curX = fw.read16(oa + ADDR.OE_CURRENT_X)
    local curY = fw.read16(oa + ADDR.OE_CURRENT_Y)
    local cur_mt = fw.read8(oa + 0x1E)
    fw.log(string.format("[diag] player on fixture tile (%d,%d) mtb=0x%02X",
        curX, curY, cur_mt))
    fw.assert_true(cur_mt == 0x02, "player starts on tall-grass tile")
    fw.screenshot("/tmp/mgba-demo-03-walk.png")

    -- 4) Open the bag.
    fw.log(">>> Opening bag...")
    fw.press("START"); fw.wait_frames(60)
    fw.screenshot("/tmp/mgba-demo-04-menu.png")
    fw.press("A");     fw.wait_frames(120)
    fw.screenshot("/tmp/mgba-demo-05-bag.png")

    fw.log(">>> Switching to KEY ITEMS pocket...")
    fw.press("RIGHT"); fw.wait_frames(60)
    fw.screenshot("/tmp/mgba-demo-06-key-items.png")

    fw.log(">>> Selecting POKERADAR -> USE...")
    fw.press("A"); fw.wait_frames(60)
    fw.screenshot("/tmp/mgba-demo-07-item-menu.png")
    fw.press("A"); fw.wait_frames(120)
    fw.screenshot("/tmp/mgba-demo-08-after-use.png")

    fw.log(">>> Waiting for patches to appear...")
    fw.wait_frames(240)
    log_state("post-activate")
    fw.screenshot("/tmp/mgba-demo-09-patches.png")

    fw.assert_true((pr.get_flags() & pr.FLAG_PATCHES_ACTIVE) ~= 0,
        "PATCHES_ACTIVE flag set after radar use")
    fw.assert_eq(pr.get_charges(), 0,
        "charge consumed by radar use")

    fw.log(">>> Walking into a patch...")
    fw.hold("UP",   24); fw.wait_frames(20)
    fw.hold("LEFT", 24); fw.wait_frames(20)
    fw.hold("DOWN", 24); fw.wait_frames(20)
    fw.hold("RIGHT",24); fw.wait_frames(60)
    log_state("post-step")

    fw.wait_frames(120)
    fw.finish()
end)
